--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/ItsToxicGG/FlyDX
build-by-default: true
branches:
- main
projects:
  FlyDX:
    path: ""
    libs:
      - src: Vecnavium/FormsUI/libFormsUI
        version: ^1.1.2
...
